const express=require('express')
const bodyParser=require('body-parser')
const port=process.env.PORT || 5000
const {Snowflake}=require('@theinternetfolks/snowflake')
const app=express()
const cookieParser=require('cookie-parser')
const cors=require('cors')
const mongoose=require('mongoose')
mongoose.connect(process.env.MONGODB_URI).then(()=>{
    console.log('connected')
})
mongoose.pluralize(false)
app.use(bodyParser.urlencoded({extended:true}))
app.use(bodyParser.json())
app.use(cors())
app.use(cookieParser())
const community=require('./routes/community')
const date=new Date()
// require('dotenv').config()
const role=require('./routes/role')
const user=require('./routes/user')
const member=require('./routes/member')
app.use('/v1/role',role)
app.use('/v1/community',community)
app.use('/v1/auth',user)
app.use('/v1/member',member)
app.listen(port,()=>{
    console.log('successfully connected')
})